---
title: "R Notebook"
author: "Bruna Barbosa"
output: html_notebook
---

### 1.Dados
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
library(GGally)
library(here)
library(plotly)
library(ggplot2)
library(reshape2)
library(chron)
library(boot)

theme_set(theme_bw())
```


```{r echo=TRUE, message=FALSE, warning=FALSE}
users_data_from_github = read_csv(here("data/github-users-committing-filetypes.csv"),
                col_types = cols(
                      .default = col_double(),
                      file_extension = col_character(),
                      month_day = col_integer(),
                      the_month = col_integer(),
                      the_year = col_integer(),
                      users = col_integer()
                    ))

non_programming_languages <- c("pdf", "md", "html", "txt", "json", "xml", "css", "yml", "scss", "jpg",
                   "lock", "png", "gradle", "config", "ico", "gif", "svg", "csproj", "rst",
                   "map", "ttf", "yaml", "pbxproj", "less", "woff", "eot")

programming_languages <- subset(users_data_from_github, !(file_extension %in% non_programming_languages))

programming_languages_sorted <- programming_languages %>% 
  arrange(file_extension, the_year, the_month, month_day)

##Linguagens de programacao
unique(programming_languages_sorted$file_extension)

programming_languages_sorted <- programming_languages_sorted %>% 
  mutate(date_formated = paste(the_year, the_month, month_day, sep="-")) %>% 
  mutate(is_weekend = wday(date_formated, label = FALSE, abbr = TRUE, ordered = FALSE))

```
### 1. Linguagens mais recentes sao mais populares do que linguagens mais antigas?

  Nesta analise utilizaremos 2 grupos que contem 3 linguagens cada, o primeiro grupo com linguagens dos anos 90 e outro com linguagens que surgiram apartir do ano 2000.
  
1. GRUPO 1 [1970-1990]: java, c e sql
2. GRUPO 2 [2000-2018]: go, typescript e swift

```{r}


```
