---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

### 1. Os Dados
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(GGally)
library(here)
library(plotly)
library(ggplot2)
library(reshape2)
library(chron)

theme_set(theme_bw())
```


```{r echo=TRUE, message=FALSE, warning=FALSE, r echo=TRUE}
users_data_from_github = read_csv(here("data/github-users-committing-filetypes.csv"),
                col_types = cols(
                      .default = col_double(),
                      file_extension = col_character(),
                      month_day = col_integer(),
                      the_month = col_integer(),
                      the_year = col_integer(),
                      users = col_integer()
                    ))

non_programming_languages <- c("pdf", "md", "html", "txt", "json", "xml", "css", "yml", "scss", "jpg",
                   "lock", "png", "gradle", "config", "ico", "gif", "svg", "csproj", "rst",
                   "map", "ttf", "yaml", "pbxproj", "less", "woff", "eot")

programming_languages <- subset(users_data_from_github, !(file_extension %in% non_programming_languages))

programming_languages_sorted <- programming_languages %>% 
  arrange(file_extension, the_year, the_month, month_day)

##Linguagens de programacao
unique(programming_languages_sorted$file_extension)

programming_languages_sorted <- programming_languages_sorted %>% 
  mutate(date_formated = paste(the_year, the_month, month_day, sep="-")) %>% 
  mutate(is_weekend = is.weekend(date_formated))

```

### 2. Popularidade na amostra

#### 2.2 JavaScript

```{r echo=TRUE}
js <- programming_languages_sorted %>% 
  filter(file_extension == "js") %>% 
  group_by(file_extension, the_year, the_month) %>%
  summarise(monthly_users = sum(users)) 
  

year <- as.factor(js$the_year)
sp <- ggplot(js, aes(x = the_month,y = monthly_users, color = year)) +
    geom_point(size=1) + xlab("Month") + ylab("Users") + 
    geom_line() + 
    ggtitle("Java Script") +
    geom_hline(aes(yintercept=median(monthly_users)),colour="#315b7d", linetype="dashed")

#sp <- sp + facet_grid(rows = vars(js$the_year)) + theme(legend.position="none")

ggplotly(sp)

```



```{r echo=TRUE}
js_fds <- programming_languages_sorted %>% 
  filter(file_extension == "js") %>% 
  filter(is_weekend == TRUE) %>% 
  group_by(file_extension, the_year, the_month) %>%
  summarise(monthly_users = sum(users)) 
  

sp <- ggplot(js_fds, aes(x = the_month,y = monthly_users, color = year)) +
    geom_point(size=1) + xlab("Month") + ylab("Users") + 
    geom_line() + 
    ggtitle("Java Script") +
    geom_hline(aes(yintercept=median(monthly_users)),colour="#315b7d", linetype="dashed")

#sp <- sp + facet_grid(rows = vars(the_year)) + theme(legend.position="none")

ggplotly(sp)%>% 
  layout(showlegend = FALSE)

```

#### 2.2 Go

```{r echo=TRUE}
go <- programming_languages_sorted %>% 
  filter(file_extension == "go") %>% 
  group_by(file_extension, the_year, the_month) %>%
  summarise(monthly_users = sum(users)) 
  

sp <- ggplot(go, aes(x = the_month,y = monthly_users, color = as.factor(js$the_year))) +
    geom_line() + 
    geom_point(size=1) + xlab("Month") + ylab("Users") + 
    ggtitle("Go") +
    geom_hline(aes(yintercept=median(monthly_users)),colour="#315b7d", linetype="dashed")

sp <- sp + facet_grid(rows = vars(the_year)) + theme(legend.position="none")

ggplotly(sp)%>% 
  layout(showlegend = FALSE)

```


### 3.Bootstrap
